version: '2.3'

services:
  api:
    restart: "no"
    mem_limit: 4G
    container_name: api

    build: 
      context: ./api
      dockerfile: Dockerfile
    
    volumes:
      - ./api:/api

    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 5041"

    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      EMBEDDER_URL: ${EMBEDDER_URL}

    ports:
      - 5041:5041
    depends_on:
      - embedder
      - postgres

  embedder:
    restart: always
    container_name: embedder
    mem_limit: 4G

    build:
      context: ./embedder
      dockerfile: Dockerfile
      
    volumes:
      - ./embedder:/embedder
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 5043"
    ports:
      - 5043:5043

  postgres:
    restart: always
    container_name: postgres
    mem_limit: 100m
    image: postgres:13.3
    
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    command: "-p 5044"
    ports:
      - 5044:5044
  
  streamlit:
    container_name: streamlit
    build: 
      context: ./streamlit
      dockerfile: Dockerfile

    volumes:
      - ./streamlit:/streamlit

    command: ['streamlit', 'run', 'ui.py']

    ports:
      - 8501:8501
