CLS_LABELS = {
    0: "Danger Ahead",
    1: "Give Way",
    2: "Go Left or Straight",
    3: "Go Straight",
    4: "Huddle Road",
    5: "Left Sharp Curve",
    6: "No Entry",
    7: "No Over Taking Trucks",
    8: "No Stopping",
    9: "No Waiting",
    10: "Pedestrian",
    11: "Right Sharp Curve",
    12: "RoundAbout",
    13: "Speed Limit 20",
    14: "Speed Limit 30",
    15: "Speed Limit 50",
    16: "Speed Limit 60",
    17: "Speed Limit 70",
    18: "Stop",
    19: "Truck Sign",
    20: "Turn Left",
    21: "Turn Right",
    22: "bicycle",
    23: "broken_white_line",
    24: "bus_stop",
    25: "children",
    26: "continuous_white_line",
    27: "crossing",
    28: "crosswalk",
    29: "do_not_enter",
    30: "do_not_stop",
    31: "do_not_turn_left",
    32: "do_not_turn_right",
    33: "do_not_u_turn",
    34: "double_yellow_line",
    35: "enter_left_lane",
    36: "give_way",
    37: "green_light",
    38: "lanes_merging",
    39: "left_lane_enter",
    40: "left_right_lane",
    41: "left_sharp_curve",
    42: "left_turn",
    43: "light_traffic",
    44: "narrow_road",
    45: "no_entry",
    46: "no_left_turn",
    47: "no_overtaking",
    48: "no_overtaking_truck",
    49: "no_parking",
    50: "no_passing",
    51: "no_right_turn",
    52: "no_stop",
    53: "no_waiting",
    54: "parking",
    55: "ped_crossing",
    56: "ped_zebra_cross",
    57: "pedestrain_crossing_prohibition",
    58: "railway_crossing",
    59: "red_light",
    60: "refueling",
    61: "right_sharp_curve",
    62: "right_turn",
    63: "road_main",
    64: "road_work",
    65: "school_nearby",
    66: "speed_bump",
    67: "speed_limit_100",
    68: "speed_limit_120",
    69: "speed_limit_20",
    70: "speed_limit_30",
    71: "speed_limit_40",
    72: "speed_limit_50",
    73: "speed_limit_60",
    74: "speed_limit_70",
    75: "speed_limit_80",
    76: "stop",
    77: "t_intersection_l",
    78: "traffic_light",
    79: "truck",
    80: "u-turn_ahead",
    81: "u_turn",
    82: "warning",
    83: "yellow_box",
    84: "yellow_light",
}

WEIGHTS_DIR = "yolo_weights"

YDL_CONFIG = {
    "quiet": True,
    "no-warnings": False,
    "ignore-errors": False,
    "no-overwrites": True,
    "format": "best",
    "keepvideo": True,
}

DOWNLOAD_VIDEO_DIR = "example_images/download_videos"
LABELED_VIDEO_DIR = "example_images/labeled_videos"